# MAIN CONFIG FILE FOR AFK REWARDS

# CONFIGURATION STARTS HERE:
afk-region: "afk" # Change this to your WorldGuardRegion
afk-time-limit: 1800 # time in seconds before the player is considered AFK

# These are the messages that are sent to the player when they use the command
Prefix: '&7[&bAFK Rewards&7]'
no-permission: '&cYou do not have permission to use this command'
reload: '&aSuccessfully reloaded the config!'

afk-rewards:
  - time: 300
    reward: "diamond x5"
  - time: 600
    reward: "emerald x10"
  - time: 900
    reward: "golden apple x1"
