name: AFK_Rewards
version: 1.0
api-version: '1.19'
main: me.Incbom.afk.Main
softdepend: [Vault]
commands:
  afk:
    description: AFK main command
    usage: '/afk'
    aliases: [afkrewards, afk]
    permission: afk.main
    permission-message: You do not have permission to use this command

